services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=omkar
      - MONGO_INITDB_ROOT_PASSWORD=omkar
  mongo-expres:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=omkar
      - ME_CONFIG_MONGODB_ADMINPASSWORD=omkar
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}